name: CI/CD Python Calculadora

on:
  workflow_dispatch:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

env:
  PYTHON_VERSION: '3.9'


jobs:
  test:
    name: Testes
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: ${{ env.PYTHON_VERSION }}

      - name: Install dependencies
        run: bash scripts/install_dependencies.sh

      - name: Run tests
        run: |
          python -m pytest tests/teste_calculadora.py --html=test-report.html --self-contained-html

      - name: Upload test report
        uses: actions/upload-artifact@v4
        with:
          name: test-report
          path: test-report.html

  start_notification:
    name: Notificação Inicial
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: ${{ env.PYTHON_VERSION }}
      - name: Enviar e-mail inicial
        run: |
          python scripts/send_email.py --sender "${{ secrets.GMAIL_EMAIL }}" --password "${{ secrets.GMAIL_APP_PASSWORD }}" --receiver "${{ secrets.DESTINATARIO_EMAIL }}" --tipo "start"

  build:
    name: Empacotamento
    needs: [test, start_notification]
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: ${{ env.PYTHON_VERSION }}
      
      - name: Install build tools
        run: |
          python -m pip install --upgrade pip setuptools wheel
      
      - name: Build package
        run: |
          python setup.py sdist bdist_wheel
      
      - name: Upload package
        uses: actions/upload-artifact@v4
        with:
          name: calculadora-package
          path: dist/*

  end_notification:
    name: Notificação de fim
    needs: build
    runs-on: ubuntu-latest
    if: always()  # Executa mesmo se a build falhar
    steps:
      - uses: actions/checkout@v4
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: ${{ env.PYTHON_VERSION }}

      - name: Determinar status
        id: status_check
        run: |
          if [[ "${{ needs.build.result }}" == "success" ]]; then
            echo "STATUS=success" >> $GITHUB_OUTPUT
          else
            echo "STATUS=failure" >> $GITHUB_OUTPUT
        shell: bash

      - name: Enviar e-mail final
        run: |
          python scripts/send_email.py --sender "${{ secrets.GMAIL_EMAIL }}" --password "${{ secrets.GMAIL_APP_PASSWORD }}" --receiver "${{ secrets.DESTINATARIO_EMAIL }}" --tipo "end" --status "${{ steps.status_check.outputs.STATUS }}"

