name: CI/CD Python Calculadora

on:
  workflow_dispatch:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

env:
  PYTHON_VERSION: '3.9'


jobs:
  test:
    name: Testes
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: ${{ env.PYTHON_VERSION }}

      - name: Install dependencies
        run: bash scripts/install_dependencies.sh

      - name: Run tests
        run: |
          python -m pytest tests/teste_calculadora.py --html=test-report.html --self-contained-html

      - name: Upload test report
        uses: actions/upload-artifact@v4
        with:
          name: test-report
          path: test-report.html

  build:
    name: Empacotamento
    needs: test
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: ${{ env.PYTHON_VERSION }}
      
      - name: Install build tools
        run: |
          python -m pip install --upgrade pip setuptools wheel
      
      - name: Build package
        run: |
          python setup.py sdist bdist_wheel
      
      - name: Upload package
        uses: actions/upload-artifact@v4
        with:
          name: calculadora-package
          path: dist/*

  start_notification:
    name: Notificação Inicial
    needs: test
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: ${{ env.PYTHON_VERSION }}
      - name: Enviar e-mail inicial
        env:
          REMETENTE: ${{ secrets.OUTLOOK_EMAIL }}
          SENHA: ${{ secrets.OUTLOOK_PASSWORD }}
          DESTINATARIO: ${{ secrets.DESTINATARIO_EMAIL }}
        run: |
          python scripts/send_email.py