name: CI/CD Python Calculadora

on:
  workflow_dispatch:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

env:
  PYTHON_VERSION: '3.9'


jobs:
  test:
    name: Testes
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: ${{ env.PYTHON_VERSION }}

      - name: Install dependencies
        run: bash scripts/install_dependencies.sh

      - name: Run tests
        run: |
          python -m pytest tests/teste_calculadora.py --html=test-report.html --self-contained-html

      - name: Upload test report
        uses: actions/upload-artifact@v4
        with:
          name: test-report
          path: test-report.html

  build:
    name: Empacotamento
    needs: test
    runs-on: ubuntu-latest

    steps:
    - uses: actions/upload-artifact@v4 
    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: ${{ env.PYTHON_VERSION }}

    - name: Build package
      uses: actions/upload-artifact@v4 
      with:
        name: calculadora-package
        path: dist/*